title: Samuel Schuler
description: Skulpturen aus Stein und Beton
remote_theme: jekyll/minima

minima:
  social_links:
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/samuelschuler.de/"
      - title: Mail
      icon: envelope
      url: "mailto:sam-schuler@web.de"
  hide_site_feed_link: true
