title: Samuel Schuler
description: Skulpturen aus Stein und Beton
author:
    author: Samuel Schuler
    email: sam-schuler@web.de

remote_theme: jekyll/minima
minima:
  social_links:
    - title: Instagram
      icon: instagram
      url: "https://www.instagram.com/samuelschuler.de/"
  hide_site_feed_link: true
